function GetSongColor(songtit)

	local Color = {
		--New licenses and Konami Originals- (Green)
		["GRADUATION ~それぞれの明日~"] = "#00FF4A",
		["1998"] = "#00FF4A",
		["LA COPA DE LA VIDA"] = "#00FF4A",
		["LOVE ♡ SHINE"] = "#00FF4A",
		["WE ARE THE CHAMPIONS (Factory Team Remix)"] = "#00FF4A",
		["WE WILL ROCK YOU"] = "#00FF4A",
		["I DO I DO I DO"] = "#00FF4A",
		["HYPER EUROBEAT"] = "#00FF4A",
		["MEMORIES"] = "#00FF4A",
		["VANITY ANGEL"] = "#00FF4A",
		["CRASH!"] = "#00FF4A",
		["SEÑORITA Speedy Mix"] = "#00FF4A",
		["SPEED OVER BEETHOVEN"] = "#00FF4A",
		["IRRESISTIBLEMENT"] = "#00FF4A",
		["BURNIN' THE FLOOR (MOMO MIX)"] = "#00FF4A",
		["CARTOON HEROES (Speedy Mix)"] = "#00FF4A",
		["TEARS"] = "#00FF4A",
		["bag"] = "#00FF4A",
		--Returning licenses- (Blue)
		["LET'S GET DOWN"] = "#00C6FF",
		["TELEPHONE OPERATOR (Club MIX)"] = "#00C6FF",
		["BUTTERFLY"] = "#00C6FF",
		["EL RITMO TROPICAL"] = "#00C6FF",
		["DAM DARIRAM"] = "#00C6FF",
		["SYNCHRONIZED LOVE (Red Monster Hyper Mix)"] = "#00C6FF",
		["LITTLE BITCH"] = "#00C6FF",
		["SAINT GOES MARCHING (REMIX)"] = "#00C6FF",
		["IF YOU WERE HERE"] = "#00C6FF",
		["RHYTHM AND POLICE (K.O.G G3 Mix)"] = "#00C6FF",
		["GET UP'N MOVE"] = "#00C6FF",
		["I believe in miracles"] = "#00C6FF",
		["CAPTAIN JACK (GRANDALE REMIX)"] = "#00C6FF",
		--New Bemani Crossovers- (Yellow)
		["HOLD ON ME"] = "#FFFF00",
		["Happy Wedding"] = "#FFFF00",
		["Miracle Moon ~L.E.D.LIGHT STYLE MIX~"] = "#FFFF00",
		["White Lovers"] = "#FFFF00",
		["air"] = "#FFFF00",
		["I'm gonna get you!"] = "#FFFF00",
		["JANEJANA"] = "#FFFF00",
		["♡LOVE²シュガ→♡"] = "#FFFF00",
		["三毛猫ロック"] = "#FFFF00",
		["Pink Rose"] = "#FFFF00",
		["STAY (Organic house Version)"] = "#FFFF00",
		["Destiny lovers"] = "#FFFF00",
		["蒼い衝動(for EXTREME)"] = "#FFFF00",
		["feeling of love"] = "#FFFF00",
		["KISS ME ALL NIGHT LONG"] = "#FFFF00",
		["Last Message"] = "#FFFF00",
		["MOBO★MOGA"] = "#FFFF00",
		["Gamelan de Couple"] = "#FFFF00",
		["LA BAMBA"] = "#FFFF00",
		["Colors(for EXTREME)"] = "#FFFF00",
		["KISS KISS KISS"] = "#FFFF00",
		["魔法の扉 (スペースマコのテーマ)"] = "#FFFF00",
		["BE LOVIN"] = "#FFFF00",
		["L'amour et la liberté (DDR ver.)"] = "#FFFF00",
		["Frozen Ray (for EXTREME)"] = "#FFFF00",
		["JET WORLD"] = "#FFFF00",
		["大見解"] = "#FFFF00",
		["V(for EXTREME)"] = "#FFFF00",
		["Heaven is a '57 metallic gray (gimmix)"] = "#FFFF00",
		["TwinBee ~Generation X~"] = "#FFFF00",
		["321 STARS"] = "#FFFF00",
		["A"] = "#FFFF00",
		["stoic(EXTREME version)"] = "#FFFF00",
		["sync(EXTREME version)"] = "#FFFF00",
		["Across the nightmare"] = "#FFFF00",
		["xenon"] = "#FFFF00",
		["The Least 100sec"] = "#FFFF00",
		["桜"] = "#FFFF00",
		--Home Version and Solo Mix- (Purple)
		["CUTIE CHASER (MORNING MIX)"] = "#E700FF",
		["DROP THE BOMB (System S.F. Mix)"] = "#E700FF",
		["SKY HIGH"] = "#E700FF",
		["DYNAMITE RAVE (Down Bird SOTA Mix)"] = "#E700FF",
		["Do It Right (Harmonized 2Step Mix)"] = "#E700FF",
		["Look To The Sky (True Color Mix)"] = "#E700FF",
		["SO IN LOVE"] = "#E700FF",
		["Kind Lady"] = "#E700FF",
		["AM-3P (303 BASSMIX)"] = "#E700FF",
		--Boss Songs- (Red)
		["Dance Dance Revolution"] = "#FF0000",
		["TRIP MACHINE survivor"] = "#FF0000",
		["PARANOIA survivor"] = "#FF0000",
		["PARANOIA survivor MAX"] = "#FF0000",
		["The legend of MAX"] = "#FF0000",
	}

	return Color[songtit] or "#FFFFFF";
end;